const signup = async (parent, args, context, info) => {
    try {
        console.log("signup")
    } catch (error) {
        return error
    }
}

const login = async (parent, args, context, info) => {
    try {
        console.log("signup")
    } catch (error) {
        return error
    }
}

const updateUser = async (parent, args, context, info) => {
    try {
        console.log("signup")
    } catch (error) {
        return error
    }
}

const deleteUser = async (parent, args, context, info) => {
    try {
        console.log("signup")
    } catch (error) {
        return error
    }
}

const createNote = async (parent, args, context, info) => {
    try {
        console.log("createNote")
    } catch (error) {
        return error
    }
}

const updateNote = async (parent, args, context, info) => {
    try {
        console.log("updateNote")
    } catch (error) {
        return error
    }
}

const deleteNote = async (parent, args, context, info) => {
    try {
        console.log("deleteNote")
    } catch (error) {
        return error
    }
}

const addPage = async (parent, args, context, info) => {
    try {
        console.log("addPage")
    } catch (error) {
        return error
    }
}

const editPage = async (parent, args, context, info) => {
    try {
        console.log("editPage")
    } catch (error) {
        return error
    }
}

const deletePage = async (parent, args, context, info) => {
    try {
        console.log("deletePage")
    } catch (error) {
        return error
    }
}

module.exports =  {
    signup,
    login,
    updateUser,
    deleteUser,
    createNote,
    updateNote,
    deleteNote,
    addPage,
    editPage,
    deletePage,
}

